---
- name: "apt update and upgrade"
  apt:
    upgrade: 'safe'
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: '43200'

- name: "install basic packages"
  apt:
    name:
      - apt-transport-https
      - atop
      - clamav
      - clamav-daemon
      - clamtk
      - curl
      - git
      - gnupg
      - gnupg-agent
      - gufw
      - htop
      - iotop
      - lsof
      - ncdu
      - net-tools
      - ssh
      - sysstat
      - traceroute
      - tree
      - ufw
      - vim
      - wget
      - whois
    state: present
    update_cache: yes
