users:
    - name: hth
      password: ENC[AES256_GCM,data:Pqx9dtrTaQU/GyXyKqXlGSCbUZZR0mInobKyfydXUrDfepim7EF5T6Xj4lpgMcg+mMKlU7dtBrySYnnwNUemwoW2Jz8ZfSbuEc8Kro9u8BQ8KX+os81MHvh6HLc6Sk/cr9gntf75cjvUZg==,iv:nXB83lge4aAAewQHpPj4oEfs7EDyPki6nnObx8rff5w=,tag:WTp+gKvPNRy4SnN1h/3UDg==,type:str]
      groups:
        - adm
        - cdrom
        - sudo
        - dip
        - plugdev
        - users
        - lpadmin
      shell: /bin/bash
      ssh_keys:
        - ENC[AES256_GCM,data:qRnvipRbrBIkWxZ7Zw973EntG2QHTMt3DoibuKaUeBpu3qp4Phw1/YmoOY6C+tvRemUDrSlwOgllx06Opd7YaAMqTy1MMT82BTXG0yvhT5KduggQUgy6b9Xg3BQrE/KJEg==,iv:hksk/SrZzUgE0uf2qpDR4aobuaqiAgASmnrhLQi0DEk=,tag:KruzgNtnPKhn6sJu+S1hSA==,type:str]
        - ENC[AES256_GCM,data:hyUB4MNRtxym33ESOFm7hys+Chu2CMN6iGRT/7j7lGJyjMw0xa0mrbespmgRSbikHYGa84t11FH9r8OiXdkT8YvZaYXKfp89PqsJ8Jt1bZJVCG3WYXCgv9YREk0oiZLYKJuwtyt6,iv:tv0jUKsyRY+mMl7vX/XPO+GPnryMhmX0mAnlccthyIA=,tag:+5XK4VRT3EImTpb8p3by6Q==,type:str]
sops:
    age:
        - recipient: age13kmzf9h8dzqj6casmj9yq5m2jk9hjr2y329tjjv4zr885q87u4uq4uwgv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMjZBb1F5dXdlajBmQlZw
            NnFqOEFFODlPSWlBZyt3bTZjODQ1dThOczNrClJrRFZHQ3paK0lNNlFyMDlMVU1T
            ZDhsRDduZjB0MC8rYVljRkRlRzRBM28KLS0tIHNjZ0w4aUVEWmdYU2pzSVhIWnA1
            ZGt5Zm5ycXZVL2NnTTdkYWhTSGtrc1kKdkvtbRfAqvznwciC/lRMOzaCLLnZ/Qfz
            igMM7oQc/HcAAp1r2Yjws3QNvYq2SjFzL83bsBQxVrah0I+RPFl/3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T17:39:09Z"
    mac: ENC[AES256_GCM,data:tHunrWq8zsrqzGkYAsmj7kIxTPaoBRt84ec+V7QTfS2+1cOBkLJ62dQ5Sxp9jx6NO+FIn07FJ+GgWoExxdNQRqJSAq9S7HbSbZzqO1Ip7K0fXr7P4HrBG4mtk/NhKQeIRoAuNUGg0k3iRoBarcOEhRGotlegvCJjDjNoAfxdRaI=,iv:IRz+MSTooBJRxqL0SaYkLe581zTljiU3HBTW6EBVpXk=,tag:+/uSYJOC/4zNR5F+ChnZgQ==,type:str]
    encrypted_regex: ^(password|ssh_keys)$
    version: 3.12.2
