---
- name: Validate user structure
  assert:
    that:
      - item.name is string
      - item.shell is not defined or item.shell is string
  loop: "{{ users }}"

- name: Add the users with a bash shell, appending the user groups
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    create_home: yes
    groups: "{{ item.groups | join(',') if item.groups is iterable else item.groups | default(omit) }}"
    append: yes
  loop: "{{ users }}"

# - name: Add single ssh key to user profile
#   authorized_key:
#     user: "{{ item.name }}"
#     key: "{{ item.ssh_key }}"
#   loop: "{{ users }}"
#  when: item.ssh_key is defined

- name: Add several ssh key to user profile
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  loop: "{{ users | subelements('ssh_keys', skip_missing=True) }}"
  when: item.0.ssh_keys is defined
# - debug:
#     msg: "User={{ item.0.name }} Key={{ item.1 }}"
#  loop: "{{ users | subelements('ssh_keys', skip_missing=True) }}"
