---
- name: Debian install
  apt:
    name: "{{ tools_packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Arch install
  community.general.pacman:
    name: "{{ tools_packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Archlinux"
