[k3s_servers]
master ansible_host=192.168.56.10

[k3s_agents]
worker1 ansible_host=192.168.56.11
worker2 ansible_host=192.168.56.12

[coreos:children]
k3s_servers
k3s_agents

[coreos:vars]
ansible_user=core
ansible_python_interpreter=/usr/bin/python3
