[k3s_server_init]
coreos-master1 ansible_host=192.168.56.10

[k3s_server_join]
coreos-master2 ansible_host=192.168.56.11
coreos-master3 ansible_host=192.168.56.12

[k3s_agents]
coreos-worker1 ansible_host=192.168.56.13
coreos-worker2 ansible_host=192.168.56.14

[k3s_servers:children]
k3s_server_init
k3s_server_join

[coreos:children]
k3s_server_init
k3s_server_join
k3s_agents

[coreos:vars]
ansible_user=core
ansible_python_interpreter=/usr/bin/python3
