---
- name: Load vars (Arch only)
  include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"
  when: ansible_facts['os_family'] == "Archlinux"

- name: Load OS tasks (Arch only)
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"
  when: ansible_facts['os_family'] == "Archlinux"
