---
- name: "install tools packages"
  apt:
    name:
      - ack
      - bat
      - cifs-utils
      - direnv
      - dirmngr
      - eza
      - fdupes
      - figlet
      - gufw
      - ipcalc
      - jq
      - meld
      - neofetch
      - p7zip-full
      - pdftk
      - shellcheck
      - shutter
      - silversearcher-ag
      - testssl.sh
      - tilix
      - tmux
      - tree
      - unzip
      - xclip
      - zip
      - zsh
    state: present
    update_cache: yes
