Vagrant.configure("2") do |config|
  config.vm.box               = "ubuntu-client"
  config.vm.hostname          = "ubuntu-client"
  config.ssh.private_key_path = File.join(__dir__, "../keys/id_ed25519")
  config.ssh.insert_key       = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus   = 2
    # vb.customize ["modifyvm", :id, "--nic1", "bridged"]
    # vb.customize ["modifyvm", :id, "--bridgeadapter1", "enx00e04c7030d9"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook    = "../../ansible/playbooks/workstation.yml"
    ansible.config_file = "../../ansible/ansible.cfg"
    ansible.become      = true
    # ansible.verbose     = "v"
  end
end
