---
- name: Mount Host VBox Guest Additions
  mount:
    path: /mnt/vbox
    src: /dev/sr0
    fstype: iso9660
    state: mounted

- name: Wait for CDROM device
  wait_for:
    path: /dev/sr0
    timeout: 30

- name: Check VBox ISO content
  stat:
    path: /mnt/vbox/VBoxLinuxAdditions.run
  register: vbox_iso

- name: Fail if ISO not mounted correctly
  fail:
    msg: "VBoxGuestAdditions ISO not mounted correctly"
  when: not vbox_iso.stat.exists

- name: Install build dependencies for VBox
  apt:
    name: "{{ dependency_packages }}"
    state: present
    update_cache: true

- name: Install VBox Guest Additions
  command: sh /mnt/vbox/VBoxLinuxAdditions.run
  args:
    creates: /usr/sbin/VBoxService
  register: vbox_install
  failed_when: vbox_install.rc not in [0, 2]
- debug:
    var: vbox_install.stdout_lines

- name: Unmount ISO
  mount:
    path: /mnt/vbox
    state: unmounted

- name: Stop VBox services (Debian)
  service:
    name: vboxadd-service
    state: stopped
  when:
    - ansible_facts['os_family'] == "Debian"
    - vbox_install is changed
  ignore_errors: true

- name: Reboot only if VBox was installed
  reboot:
  when: vbox_install is changed
