---
- name: Load OS specific vars
  include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Install VirtualBox Guest Additions
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"
