---
# ---------------------------------------------------------------------------
# Install k3s server
# ---------------------------------------------------------------------------
- name: Install k3s server
  hosts: k3s_servers
  become: true

  roles:
    - k3s/server

# ---------------------------------------------------------------------------
# Install k3s agents
# ---------------------------------------------------------------------------
- name: Install k3s agents
  hosts: k3s_agents
  become: true

  roles:
    - k3s/agent
