---
# ---------------------------------------------------------------------------
# Initialize K3s cluster
# ---------------------------------------------------------------------------
- name: Initialize K3s cluster
  hosts: k3s_server_init
  become: true
  roles:
    - k3s/server-init

# ---------------------------------------------------------------------------
# Join K3s servers
# ---------------------------------------------------------------------------
- name: Join K3s servers
  hosts: k3s_server_join
  become: true
  roles:
    - k3s/server-join

# ---------------------------------------------------------------------------
# Install K3s agents
# ---------------------------------------------------------------------------
- name: Install K3s agents
  hosts: k3s_agents
  become: true
  roles:
    - k3s/agent
    - coreos-iscsi
