Vagrant.configure("2") do |config|
  config.vm.box               = "manjaro-client"
  config.vm.hostname          = "manjaro-client"
  config.ssh.private_key_path = File.join(__dir__, "../keys/id_ed25519")
  config.ssh.insert_key       = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus   = 2
    # vb.customize ["modifyvm", :id, "--nic1", "bridged"]
    # vb.customize ["modifyvm", :id, "--bridgeadapter1", "enx00e04c7030d9"]
  end
end
